# Generated by Django 5.0 on 2025-09-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200)),
                ('vernacular_name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('threat_status', models.CharField(max_length=50)),
                ('occurrence_status', models.CharField(max_length=100)),
                ('max_size_cm', models.FloatField(blank=True, null=True)),
                ('body_shape', models.TextField(blank=True)),
                ('body_color', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('habitat_type', models.TextField(blank=True)),
                ('water_conditions', models.TextField(blank=True)),
                ('specific_locations', models.TextField(blank=True)),
                ('river_basins', models.TextField(blank=True)),
                ('districts', models.TextField(blank=True)),
                ('protected_areas', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fish Species',
                'verbose_name_plural': 'Fish Species',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
